require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Metrics/MethodLength:
  CountComments: false
  Max: 15

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: double_quotes
  Enabled: true

Metrics/BlockLength:
  Description: 'This cop checks if the length of a block exceeds some maximum value. Comment lines can optionally be ignored. The maximum allowed length is configurable. The cop can be configured to ignore blocks passed to certain methods.'
  Exclude: ['spec/**/*', 'config/**/*']
  Enabled: true

Metrics/AbcSize:
  Description: 'This cop checks that the ABC size of methods is not higher than the configured maximum. The ABC size is based on assignments, branches (method calls), and conditions. See http://c2.com/cgi/wiki?AbcMetric and https://en.wikipedia.org/wiki/ABC_Software_Metric.'
  Enabled: true
  Max: 20

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#80-character-limits'
  Max: 100
  IgnoredPatterns: ['\A\s*#'] # Comments
  Enabled: true

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-w'
  Enabled: false

Style/SymbolArray:
  Description: 'Use `%i` or `%I` for an array of symbols'
  StyleGuide: 'http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolArray'
  Enabled: false

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  Description: 'Checks for trailing comma in array literals.'
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/TrailingCommaInHashLiteral:
  Description: 'Checks for trailing comma in hash literals.'
  EnforcedStyleForMultiline: comma
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: true

Layout/MultilineOperationIndentation:
  Description: Checks indentation of binary operations that span more than one line.
  EnforcedStyle: indented
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes
  Enabled: true

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  Enabled: true

Style/ClassAndModuleChildren:
  Description: This cop checks the style of children definitions at classes and modules.
  Enabled: false

RSpec/ExampleLength:
  Description: Checks for long examples. A long example is usually more difficult to understand. Consider extracting out some behaviour, e.g. with a let block, or a helper method.
  Max: 10
  Enabled: true
